name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      
      - name: Build Docker image
        if: ${{ github.event_name == 'pull_request'}}
        uses: zvfvrv/docker-bpgpr@v1.0.1
        with:
          gh_token: ${{ secrets.TOKEN_GITHUB }}
          image_name: rose-expman
          tags: latest,beta
          tag_with_sha: true
          push: false

      - name: Build and Publish Docker image
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master'}}
        uses: zvfvrv/docker-bpgpr@v1.0.1
        with:
          gh_token: ${{ secrets.TOKEN_GITHUB }}
          image_name: rose-expman
          tags: latest,beta
          tag_with_sha: true
          push: true
    
      - name: Build and Publish Docker image DockerHub 
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master'}}
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # temporary push on a test dockerhub repo
          repository: rosesrv6/rose-expman
          tag_with_ref: true
          tags: latest,beta